# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LifePoints' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod ‘FBSDKCoreKit’
pod ‘FBSDKLoginKit’
pod ‘FBSDKShareKit’
pod 'SDWebImage'
pod ‘AWSCore’
pod ‘AWSS3’
pod ‘AWSCognito’
pod ‘Firebase’
pod ‘Firebase/Database’
pod ‘Firebase/Auth’
pod ‘NYAlertViewController’
pod 'DownPicker'



  # Pods for LifePoints

  target 'LifePointsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LifePointsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
